---
# SoC platform
:platform:		lan969x
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	1024
:mem_type:		DDR3
:device_bus_width:	x16
:active_ranks:		1
:ecc_mode:		0
:mem_profile:		ddr3_512Mx16_2B
:_2T_mode:		0
# DDR Clock of platform (Data Bus)
:clock_speed:		1866
# Board ODT setup etc
