---
# SoC platform
:platform:		lan969x
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	1024
:mem_type:		DDR4
# Density of the individual DDR chips used (DDR4 only)
:configured_density:	8G
:device_bus_width:	x16
:active_ranks:		1
:ecc_mode:		0
:mem_profile:		alliance_ddr4_512Mx16
:_2T_mode:		0
# DDR Clock of platform (Data Bus)
:clock_speed:		2400
# Board ODT setup etc
# :board:			evb9694
