---
# SoC platform
:platform:		lan969x
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	1024
:mem_type:		DDR3
:device_bus_width:	x8
:active_ranks:		1
:ecc_mode:		0
:mem_profile:		ddr3_512Mx8_2B
:_2T_mode:		0
# DDR Clock of platform (Data Bus)
:clock_speed:		1600
# Board ODT setup etc
:board:			lan969x_svb969x
