---
# SoC platform
:platform:		sparx5
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	2048
:mem_type:		DDR4
# Density of the individual DDR chips used (DDR4 only)
:configured_density:	4G
:device_bus_width:	x8
:active_ranks:		0x1
:ecc_mode:		4
:mem_profile:		ddr4_512Mx8_fullbus
# DDR Clock of platform (Data Bus)
:clock_speed:		2000
# Board ODT setup etc
:board:			pcb134
