---
# SoC platform
:platform:		sparx5
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	2048
:mem_type:		DDR3
:device_bus_width:	x8
:active_ranks:		1
:ecc_mode:		4
:mem_profile:		issi_ddr3_512Mx8
:_2T_mode:		0
# DDR Clock of platform (Data Bus)
:clock_speed:		1667
# Board ODT setup etc
:board:			pcb135
