---
# SoC platform
:platform:		sparx5
# Total Memory Size (in Mbytes)
:mem_size_mbytes:	1024
:mem_type:		DDR3
:device_bus_width:	x16
:active_ranks:		1
:ecc_mode:		0
:mem_profile:		issi_ddr3_512Mx8_16bit
:_2T_mode:		1
# DDR Clock of platform (Data Bus)
:clock_speed:		1667
# Board ODT setup etc
:board:			pcb135
# Half bus width
:enable_half_bus:	true
