---
:params:
  # NB: Default value
  :odt_nom_ddr: 48ohm
  # NB: Default value
  :drive_strength: 34ohm
:registers:
  zq1pr:
    - ZPROG_ASYM_DRV_PU: 7
    - ZPROG_ASYM_DRV_PD: 7
    - PU_ODT_ONLY: 1
    - DRV_ZDEN: 1
  zq2pr:
    - ZPROG_ASYM_DRV_PU: 7
    - ZPROG_ASYM_DRV_PD: 7
    - PU_ODT_ONLY: 1
    - DRV_ZDEN: 1
