---
:params:
  :rtt_nom_ddr: 40ohm
  :drive_strength: 34ohm
:registers:
  zq0pr:
    - PU_ODT_ONLY: 0
    - ZPROG_ASYM_DRV_PD: 13
    - ZPROG_ASYM_DRV_PU: 13
  zq1pr:
    - RESERVED_7_0: 123
    - PU_ODT_ONLY: 0
    - ZPROG_ASYM_DRV_PD: 13
    - ZPROG_ASYM_DRV_PU: 13
  zq2pr:
    - PU_ODT_ONLY: 0
    - ZPROG_ASYM_DRV_PD: 13
    - ZPROG_ASYM_DRV_PU: 13
