---
:params:
  :odt_nom_ddr: 60ohm
  :drive_strength: 34ohm
:registers:
  zq0pr:
    - PU_ODT_ONLY: 0
    - ZPROG_PU_ODT_ONLY: 7
    - ZPROG_ASYM_DRV_PD: 9
    - ZPROG_ASYM_DRV_PU: 9
  zq1pr:
    - DRV_ZDEN: 0
    - PU_ODT_ONLY: 1
    - ZPROG_PU_ODT_ONLY: 7
    - ZPROG_ASYM_DRV_PD: 7
    - ZPROG_ASYM_DRV_PU: 9
