---
- :grp: Main control registers
  :name: main
  :regs:
  - mstr
  - pwrctl
  - rfshctl0
  - rfshctl3
  - dfitmg0
  - dfitmg1
  - dfiupd0
  - dfiupd1
  - pccfg
  - crcparctl1
  - dbictl
  - dfimisc
  - ecccfg0
  - init0
  - init1
  - init3
  - init4
  - init5
  - init6
  - init7
  - sbrctl
- :grp: Timing configuration registers
  :name: timing
  :regs:
  - rfshtmg
  - dramtmg0
  - dramtmg1
  - dramtmg2
  - dramtmg3
  - dramtmg4
  - dramtmg5
  - dramtmg8
  - dramtmg9
  - dramtmg12
  - odtcfg
- :grp: Address map configuration registers
  :name: mapping
  :regs:
  - addrmap0
  - addrmap1
  - addrmap2
  - addrmap3
  - addrmap4
  - addrmap5
  - addrmap6
  - addrmap7
  - addrmap8
- :grp: DDR PHY registers
  :name: phy
  :regs:
  - dxccr
  - dsgcr
  - dcr
  - dtcr
  - dtcr0
  - dtcr1
  - pgcr2
  - schcr1
  - zq0pr
  - zq1pr
  - zq2pr
  - zqcr
  - zq0cr0
  - zq0cr1
  - zq1cr0
  - zq1cr1
- :grp: DDR PHY timing registers
  :name: phy_timing
  :regs:
  - ptr0
  - ptr1
  - ptr2
  - ptr3
  - ptr4
  - dtpr0
  - dtpr1
  - dtpr2
  - dtpr3
  - dtpr4
  - dtpr5
