---
addrmap0:
  :ADDRMAP_CS_BIT0: 31
addrmap1:
  :ADDRMAP_BANK_B0: 24
  :ADDRMAP_BANK_B1: 24
  :ADDRMAP_BANK_B2: 24
addrmap2:
  :ADDRMAP_COL_B2: 0
  :ADDRMAP_COL_B3: 0
  :ADDRMAP_COL_B4: 0
  :ADDRMAP_COL_B5: 0
addrmap3:
  :ADDRMAP_COL_B6: 0
  :ADDRMAP_COL_B7: 0
  :ADDRMAP_COL_B8: 0
  :ADDRMAP_COL_B9: 0
addrmap4:
  :ADDRMAP_COL_B10: 31
  :ADDRMAP_COL_B11: 31
addrmap5:
  :ADDRMAP_ROW_B0: 4
  :ADDRMAP_ROW_B1: 4
  :ADDRMAP_ROW_B2_10: 4
  :ADDRMAP_ROW_B11: 4
addrmap6:
  :ADDRMAP_ROW_B12: 4
  :ADDRMAP_ROW_B13: 4
  :ADDRMAP_ROW_B14: 4
  :ADDRMAP_ROW_B15: 15
addrmap7:
  :ADDRMAP_ROW_B16: 15
  :ADDRMAP_ROW_B17: 15
addrmap8:
  :ADDRMAP_BG_B0: 25
  :ADDRMAP_BG_B1: 25
